@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyNTQzYjQzNWFmNzhmMDA0NGI1N2M3ZSIsImZpcnN0bmFtZSI6ImFiZGVsYWxpIiwibGFzdG5hbWUiOiJyYWZpayIsInBvc2l0aW9uIjoiQ0xJRU5UIiwiZW1haWwiOiJhYmRlbGFsaS5yYWZpazExQGdtYWlsLmNvbSIsImFkZHJlc3MiOm51bGx9LCJjb21wYW55Ijp7Il9pZCI6IjYyNTQzYjQzNWFmNzhmMDA0NGI1N2M3YyIsIm5hbWUiOiJzb3U5aW5vIiwic3RhdHVzIjoiVU5DT01QTEVURUQifSwic3RvcmUiOnsiX2lkIjoiNjI1NDNiNDM1YWY3OGYwMDQ0YjU3YzgzIiwibmFtZSI6IlNvdTlpbm8iLCJzdWJkb21haW4iOiJzb3U5aW5vLnN0b3JlaW5vLndvcmxkIn0sInRva2VuSWQiOiI5NjY3OTZQWVpUWlQ5NjkyNzJMSUxOTVMiLCJpYXQiOjE2Nzc1NzcwOTUsImV4cCI6MTY3ODQ0MTA5NX0.kOOkRun_9GQeG239qq5-kUVBecBSCz7uT0BbGJEV7jE


###
GET https://admin.storeino.world/stores/api/themes/search?team._id=5f21374a175b5e8e309be827
X-Auth-Token: {{token}}

###
GET https://admin.storeino.world/stores/api/themes/update?team._id=5f21374a175b5e8e309be827
Content-Type: application/json
X-Auth-Token: {{token}}

{
  "team": {
    "_id": "5f21374a175b5e8e309be827",
    "name": "Storeino Team",
    "url": "https://market.storeino.com/storeino/"
  }
}



