@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdG9yZSI6eyJfaWQiOiI2NjY2Y2UwOWZmYjdlYmU0Y2MyZmNkZGIiLCJuYW1lIjoiZ29sZFRoZW1lIiwic3ViZG9tYWluIjoiZ29sZHRoZW1lLnN0b3JlaW5vLndvcmxkIn0sInVzZXIiOnsicG9zaXRpb24iOiJDTElFTlQiLCJfaWQiOiI2NjY2Y2U2N2ZmYjdlYmU0Y2MyZmNlMzQiLCJmaXJzdG5hbWUiOiJyYWphIiwibGFzdG5hbWUiOiJlZyIsImVtYWlsIjoic3RvcmVpbm9yYWphQGdtYWlsLmNvbSJ9LCJjb21wYW55Ijp7InN0YXR1cyI6IlVOQ09NUExFVEVEIiwiX2lkIjoiNjA0MGFjZTg0ZTg3MjQwOTUwYTdkOGM5IiwibmFtZSI6InN0b3JlaW5vIn0sInRva2VuSWQiOiI3NjY1NjdZSUlHQ0g2NTU1NjVSTFBTUE8iLCJpYXQiOjE3MTkwMjgzNjUsImV4cCI6MTcxOTg5MjM2NX0.9UMzYwoLRJN0bIxjbDQU1Ep21H0UZM7wmKvyZj30jgI

###
GET https://admin.storeino.world/stores/api/themes/search?name=lux
X-Auth-Token: {{token}}

###
POST https://admin.storeino.world/stores/api/themes/update?name=lux
Content-Type: application/json
X-Auth-Token: {{token}}


{
   "team": {
        "_id": "5f21374a175b5e8e309be833",
        "name": "DEVELOPMENT",
        "url": "https://market.storeino.com/storeino/"
      }
}
